/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import type {} from '@payloadcms/db-vercel-postgres'
import {
  pgTable,
  index,
  uniqueIndex,
  foreignKey,
  integer,
  uuid,
  varchar,
  timestamp,
  boolean,
  numeric,
  serial,
  jsonb,
  pgEnum,
} from '@payloadcms/db-vercel-postgres/drizzle/pg-core'
import { sql, relations } from '@payloadcms/db-vercel-postgres/drizzle'
export const enum__locales = pgEnum('enum__locales', ['fr', 'es', 'en'])
export const enum_art_vivant_type = pgEnum('enum_art_vivant_type', ['evenement', 'residence'])
export const enum_cinema_type = pgEnum('enum_cinema_type', ['seance', 'scolaire', 'rdv_cinema'])
export const enum_cinema_public = pgEnum('enum_cinema_public', [
  'children',
  'all_public',
  'all_public_avertissment',
  'forbidden_12',
  'forbidden_16',
  'forbidden_18',
])
export const enum_mediatheque_type = pgEnum('enum_mediatheque_type', ['ludotheque'])
export const enum_mediatheque_players = pgEnum('enum_mediatheque_players', [
  '1',
  '1-2',
  '1-4',
  '1-8',
  '4+',
])
export const enum_mediatheque_duration = pgEnum('enum_mediatheque_duration', [
  '15',
  '30',
  '1h',
  '1h+',
])
export const enum_mediatheque_public = pgEnum('enum_mediatheque_public', [
  '-3',
  '3+',
  '12+',
  '16+',
  '18+',
])
export const enum_exposition_type = pgEnum('enum_exposition_type', ['exposition', 'evenement'])
export const enum_parc_national_type = pgEnum('enum_parc_national_type', ['evenement', 'article'])
export const enum_autres_actualites_type = pgEnum('enum_autres_actualites_type', ['evenement'])

export const mdv_admins_sessions = pgTable(
  'mdv_admins_sessions',
  {
    _order: integer('_order').notNull(),
    _parentID: uuid('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 }),
    expiresAt: timestamp('expires_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }).notNull(),
  },
  (columns) => [
    index('mdv_admins_sessions_order_idx').on(columns._order),
    index('mdv_admins_sessions_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [mdv_admins.id],
      name: 'mdv_admins_sessions_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const mdv_admins = pgTable(
  'mdv_admins',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    fullname: varchar('fullname').notNull(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    enableAPIKey: boolean('enable_a_p_i_key'),
    apiKey: varchar('api_key'),
    apiKeyIndex: varchar('api_key_index'),
    email: varchar('email').notNull(),
    resetPasswordToken: varchar('reset_password_token'),
    resetPasswordExpiration: timestamp('reset_password_expiration', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    salt: varchar('salt'),
    hash: varchar('hash'),
    loginAttempts: numeric('login_attempts', { mode: 'number' }).default(0),
    lockUntil: timestamp('lock_until', { mode: 'string', withTimezone: true, precision: 3 }),
  },
  (columns) => [
    index('mdv_admins_updated_at_idx').on(columns.updatedAt),
    index('mdv_admins_created_at_idx').on(columns.createdAt),
    uniqueIndex('mdv_admins_email_idx').on(columns.email),
  ],
)

export const mdv_media = pgTable(
  'mdv_media',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    blurhash: varchar('blurhash'),
    prefix: varchar('prefix').default('media-mdv'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    url: varchar('url'),
    thumbnailURL: varchar('thumbnail_u_r_l'),
    filename: varchar('filename'),
    mimeType: varchar('mime_type'),
    filesize: numeric('filesize', { mode: 'number' }),
    width: numeric('width', { mode: 'number' }),
    height: numeric('height', { mode: 'number' }),
    focalX: numeric('focal_x', { mode: 'number' }),
    focalY: numeric('focal_y', { mode: 'number' }),
  },
  (columns) => [
    index('mdv_media_updated_at_idx').on(columns.updatedAt),
    index('mdv_media_created_at_idx').on(columns.createdAt),
    uniqueIndex('mdv_media_filename_idx').on(columns.filename),
  ],
)

export const mdv_media_locales = pgTable(
  'mdv_media_locales',
  {
    alt: varchar('alt').notNull(),
    id: serial('id').primaryKey(),
    _locale: enum__locales('_locale').notNull(),
    _parentID: uuid('_parent_id').notNull(),
  },
  (columns) => [
    uniqueIndex('mdv_media_locales_locale_parent_id_unique').on(columns._locale, columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [mdv_media.id],
      name: 'mdv_media_locales_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const art_vivant_other_images = pgTable(
  'art_vivant_other_images',
  {
    _order: integer('_order').notNull(),
    _parentID: uuid('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    image: uuid('image_id').references(() => mdv_media.id, {
      onDelete: 'set null',
    }),
  },
  (columns) => [
    index('art_vivant_other_images_order_idx').on(columns._order),
    index('art_vivant_other_images_parent_id_idx').on(columns._parentID),
    index('art_vivant_other_images_image_idx').on(columns.image),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [art_vivant.id],
      name: 'art_vivant_other_images_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const art_vivant = pgTable(
  'art_vivant',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    type: enum_art_vivant_type('type').notNull(),
    archive: boolean('archive').default(true),
    immanquable: boolean('immanquable').default(false),
    jeunePublic: boolean('jeune_public'),
    thumbnail: uuid('thumbnail_id').references(() => mdv_media.id, {
      onDelete: 'set null',
    }),
    date_start: timestamp('date_start', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }).notNull(),
    price: varchar('price').notNull().default('12€ Normal; 8 € Abonnée; 6 €; 6€ Réduit - 26 ans'),
    duration: varchar('duration').notNull(),
    authors: varchar('authors'),
    portfolio_authors: varchar('portfolio_authors'),
    tags: varchar('tags'),
    location: varchar('location'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('art_vivant_thumbnail_idx').on(columns.thumbnail),
    index('art_vivant_updated_at_idx').on(columns.updatedAt),
    index('art_vivant_created_at_idx').on(columns.createdAt),
  ],
)

export const art_vivant_locales = pgTable(
  'art_vivant_locales',
  {
    title: varchar('title').notNull(),
    description: jsonb('description').notNull(),
    informations_more: jsonb('informations_more'),
    genre: varchar('genre'),
    id: serial('id').primaryKey(),
    _locale: enum__locales('_locale').notNull(),
    _parentID: uuid('_parent_id').notNull(),
  },
  (columns) => [
    uniqueIndex('art_vivant_locales_locale_parent_id_unique').on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [art_vivant.id],
      name: 'art_vivant_locales_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const cinema_other_images = pgTable(
  'cinema_other_images',
  {
    _order: integer('_order').notNull(),
    _parentID: uuid('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    image: uuid('image_id').references(() => mdv_media.id, {
      onDelete: 'set null',
    }),
  },
  (columns) => [
    index('cinema_other_images_order_idx').on(columns._order),
    index('cinema_other_images_parent_id_idx').on(columns._parentID),
    index('cinema_other_images_image_idx').on(columns.image),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [cinema.id],
      name: 'cinema_other_images_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const cinema = pgTable(
  'cinema',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    type: enum_cinema_type('type').notNull(),
    archive: boolean('archive').default(false),
    immanquable: boolean('immanquable').default(false),
    jeunePublic: boolean('jeune_public'),
    thumbnail: uuid('thumbnail_id').references(() => mdv_media.id, {
      onDelete: 'set null',
    }),
    price: varchar('price')
      .notNull()
      .default('7 € Adulte; 6 € Étudiant; 5 € Moins de 13 ans; 5,8 € Abonné'),
    date_start: timestamp('date_start', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }).notNull(),
    video: varchar('video').notNull(),
    duration: varchar('duration').notNull(),
    genre: varchar('genre').notNull(),
    public: enum_cinema_public('public').default('all_public'),
    languages: varchar('languages').notNull().default('VF'),
    actors: varchar('actors'),
    directors: varchar('directors'),
    location: varchar('location'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('cinema_thumbnail_idx').on(columns.thumbnail),
    index('cinema_updated_at_idx').on(columns.updatedAt),
    index('cinema_created_at_idx').on(columns.createdAt),
  ],
)

export const cinema_locales = pgTable(
  'cinema_locales',
  {
    title: varchar('title').notNull(),
    synopsis: jsonb('synopsis').notNull(),
    informations_more: jsonb('informations_more'),
    id: serial('id').primaryKey(),
    _locale: enum__locales('_locale').notNull(),
    _parentID: uuid('_parent_id').notNull(),
  },
  (columns) => [
    uniqueIndex('cinema_locales_locale_parent_id_unique').on(columns._locale, columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [cinema.id],
      name: 'cinema_locales_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const mediatheque_other_images = pgTable(
  'mediatheque_other_images',
  {
    _order: integer('_order').notNull(),
    _parentID: uuid('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    image: uuid('image_id').references(() => mdv_media.id, {
      onDelete: 'set null',
    }),
  },
  (columns) => [
    index('mediatheque_other_images_order_idx').on(columns._order),
    index('mediatheque_other_images_parent_id_idx').on(columns._parentID),
    index('mediatheque_other_images_image_idx').on(columns.image),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [mediatheque.id],
      name: 'mediatheque_other_images_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const mediatheque = pgTable(
  'mediatheque',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    type: enum_mediatheque_type('type').notNull().default('ludotheque'),
    jeunePublic: boolean('jeune_public'),
    thumbnail: uuid('thumbnail_id').references(() => mdv_media.id, {
      onDelete: 'set null',
    }),
    price: varchar('price').notNull().default('2€ par jour; Gratuit sur place'),
    players: enum_mediatheque_players('players').notNull().default('1-4'),
    duration: enum_mediatheque_duration('duration').notNull().default('30'),
    public: enum_mediatheque_public('public').notNull().default('3+'),
    authors: varchar('authors'),
    location: varchar('location'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('mediatheque_thumbnail_idx').on(columns.thumbnail),
    index('mediatheque_updated_at_idx').on(columns.updatedAt),
    index('mediatheque_created_at_idx').on(columns.createdAt),
  ],
)

export const mediatheque_locales = pgTable(
  'mediatheque_locales',
  {
    title: varchar('title').notNull(),
    description: jsonb('description').notNull(),
    informations_more: jsonb('informations_more'),
    availability_date: varchar('availability_date'),
    genre: varchar('genre'),
    materiel: varchar('materiel'),
    id: serial('id').primaryKey(),
    _locale: enum__locales('_locale').notNull(),
    _parentID: uuid('_parent_id').notNull(),
  },
  (columns) => [
    uniqueIndex('mediatheque_locales_locale_parent_id_unique').on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [mediatheque.id],
      name: 'mediatheque_locales_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const exposition_images = pgTable(
  'exposition_images',
  {
    _order: integer('_order').notNull(),
    _parentID: uuid('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    image: uuid('image_id').references(() => mdv_media.id, {
      onDelete: 'set null',
    }),
  },
  (columns) => [
    index('exposition_images_order_idx').on(columns._order),
    index('exposition_images_parent_id_idx').on(columns._parentID),
    index('exposition_images_image_idx').on(columns.image),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [exposition.id],
      name: 'exposition_images_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const exposition_other_images = pgTable(
  'exposition_other_images',
  {
    _order: integer('_order').notNull(),
    _parentID: uuid('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    image: uuid('image_id').references(() => mdv_media.id, {
      onDelete: 'set null',
    }),
  },
  (columns) => [
    index('exposition_other_images_order_idx').on(columns._order),
    index('exposition_other_images_parent_id_idx').on(columns._parentID),
    index('exposition_other_images_image_idx').on(columns.image),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [exposition.id],
      name: 'exposition_other_images_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const exposition = pgTable(
  'exposition',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    type: enum_exposition_type('type').notNull(),
    archive: boolean('archive').default(true),
    immanquable: boolean('immanquable').default(false),
    thumbnail: uuid('thumbnail_id').references(() => mdv_media.id, {
      onDelete: 'set null',
    }),
    date_start: timestamp('date_start', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }).notNull(),
    date_end: timestamp('date_end', { mode: 'string', withTimezone: true, precision: 3 }).notNull(),
    location: varchar('location'),
    tags: varchar('tags'),
    authors: varchar('authors'),
    portfolio_authors: varchar('portfolio_authors'),
    credits_photos: varchar('credits_photos'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('exposition_thumbnail_idx').on(columns.thumbnail),
    index('exposition_updated_at_idx').on(columns.updatedAt),
    index('exposition_created_at_idx').on(columns.createdAt),
  ],
)

export const exposition_locales = pgTable(
  'exposition_locales',
  {
    title: varchar('title').notNull(),
    description: jsonb('description').notNull(),
    informations_more: jsonb('informations_more'),
    genre: varchar('genre'),
    id: serial('id').primaryKey(),
    _locale: enum__locales('_locale').notNull(),
    _parentID: uuid('_parent_id').notNull(),
  },
  (columns) => [
    uniqueIndex('exposition_locales_locale_parent_id_unique').on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [exposition.id],
      name: 'exposition_locales_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const parc_national_other_images = pgTable(
  'parc_national_other_images',
  {
    _order: integer('_order').notNull(),
    _parentID: uuid('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    image: uuid('image_id').references(() => mdv_media.id, {
      onDelete: 'set null',
    }),
  },
  (columns) => [
    index('parc_national_other_images_order_idx').on(columns._order),
    index('parc_national_other_images_parent_id_idx').on(columns._parentID),
    index('parc_national_other_images_image_idx').on(columns.image),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [parc_national.id],
      name: 'parc_national_other_images_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const parc_national = pgTable(
  'parc_national',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    type: enum_parc_national_type('type').notNull(),
    archive: boolean('archive').default(true),
    immanquable: boolean('immanquable').default(false),
    jeunePublic: boolean('jeune_public'),
    thumbnail: uuid('thumbnail_id').references(() => mdv_media.id, {
      onDelete: 'set null',
    }),
    date_start: timestamp('date_start', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }).notNull(),
    price: varchar('price').notNull().default('12€ Normal; 8 € Abonnée; 6 €; 6€ Réduit - 26 ans'),
    duration: varchar('duration').notNull(),
    authors: varchar('authors'),
    portfolio_authors: varchar('portfolio_authors'),
    tags: varchar('tags'),
    location: varchar('location'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('parc_national_thumbnail_idx').on(columns.thumbnail),
    index('parc_national_updated_at_idx').on(columns.updatedAt),
    index('parc_national_created_at_idx').on(columns.createdAt),
  ],
)

export const parc_national_locales = pgTable(
  'parc_national_locales',
  {
    title: varchar('title').notNull(),
    description: jsonb('description').notNull(),
    informations_more: jsonb('informations_more'),
    genre: varchar('genre'),
    id: serial('id').primaryKey(),
    _locale: enum__locales('_locale').notNull(),
    _parentID: uuid('_parent_id').notNull(),
  },
  (columns) => [
    uniqueIndex('parc_national_locales_locale_parent_id_unique').on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [parc_national.id],
      name: 'parc_national_locales_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const autres_actualites_other_images = pgTable(
  'autres_actualites_other_images',
  {
    _order: integer('_order').notNull(),
    _parentID: uuid('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    image: uuid('image_id').references(() => mdv_media.id, {
      onDelete: 'set null',
    }),
  },
  (columns) => [
    index('autres_actualites_other_images_order_idx').on(columns._order),
    index('autres_actualites_other_images_parent_id_idx').on(columns._parentID),
    index('autres_actualites_other_images_image_idx').on(columns.image),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [autres_actualites.id],
      name: 'autres_actualites_other_images_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const autres_actualites = pgTable(
  'autres_actualites',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    type: enum_autres_actualites_type('type').notNull(),
    archive: boolean('archive').default(true),
    jeunePublic: boolean('jeune_public'),
    thumbnail: uuid('thumbnail_id').references(() => mdv_media.id, {
      onDelete: 'set null',
    }),
    date_start: timestamp('date_start', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }).notNull(),
    price: varchar('price').notNull().default('12€ Normal; 8 € Abonnée; 6 €; 6€ Réduit - 26 ans'),
    duration: varchar('duration').notNull(),
    authors: varchar('authors'),
    portfolio_authors: varchar('portfolio_authors'),
    tags: varchar('tags'),
    location: varchar('location'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('autres_actualites_thumbnail_idx').on(columns.thumbnail),
    index('autres_actualites_updated_at_idx').on(columns.updatedAt),
    index('autres_actualites_created_at_idx').on(columns.createdAt),
  ],
)

export const autres_actualites_locales = pgTable(
  'autres_actualites_locales',
  {
    title: varchar('title').notNull(),
    description: jsonb('description').notNull(),
    informations_more: jsonb('informations_more'),
    genre: varchar('genre'),
    id: serial('id').primaryKey(),
    _locale: enum__locales('_locale').notNull(),
    _parentID: uuid('_parent_id').notNull(),
  },
  (columns) => [
    uniqueIndex('autres_actualites_locales_locale_parent_id_unique').on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [autres_actualites.id],
      name: 'autres_actualites_locales_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const payload_kv = pgTable(
  'payload_kv',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    key: varchar('key').notNull(),
    data: jsonb('data').notNull(),
  },
  (columns) => [uniqueIndex('payload_kv_key_idx').on(columns.key)],
)

export const payload_locked_documents = pgTable(
  'payload_locked_documents',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    globalSlug: varchar('global_slug'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payload_locked_documents_global_slug_idx').on(columns.globalSlug),
    index('payload_locked_documents_updated_at_idx').on(columns.updatedAt),
    index('payload_locked_documents_created_at_idx').on(columns.createdAt),
  ],
)

export const payload_locked_documents_rels = pgTable(
  'payload_locked_documents_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: uuid('parent_id').notNull(),
    path: varchar('path').notNull(),
    adminsID: uuid('mdv_admins_id'),
    mediaID: uuid('mdv_media_id'),
    art_vivantID: uuid('art_vivant_id'),
    cinemaID: uuid('cinema_id'),
    mediathequeID: uuid('mediatheque_id'),
    expositionID: uuid('exposition_id'),
    parc_nationalID: uuid('parc_national_id'),
    autres_actualitesID: uuid('autres_actualites_id'),
  },
  (columns) => [
    index('payload_locked_documents_rels_order_idx').on(columns.order),
    index('payload_locked_documents_rels_parent_idx').on(columns.parent),
    index('payload_locked_documents_rels_path_idx').on(columns.path),
    index('payload_locked_documents_rels_mdv_admins_id_idx').on(columns.adminsID),
    index('payload_locked_documents_rels_mdv_media_id_idx').on(columns.mediaID),
    index('payload_locked_documents_rels_art_vivant_id_idx').on(columns.art_vivantID),
    index('payload_locked_documents_rels_cinema_id_idx').on(columns.cinemaID),
    index('payload_locked_documents_rels_mediatheque_id_idx').on(columns.mediathequeID),
    index('payload_locked_documents_rels_exposition_id_idx').on(columns.expositionID),
    index('payload_locked_documents_rels_parc_national_id_idx').on(columns.parc_nationalID),
    index('payload_locked_documents_rels_autres_actualites_id_idx').on(columns.autres_actualitesID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_locked_documents.id],
      name: 'payload_locked_documents_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['adminsID']],
      foreignColumns: [mdv_admins.id],
      name: 'payload_locked_documents_rels_admins_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['mediaID']],
      foreignColumns: [mdv_media.id],
      name: 'payload_locked_documents_rels_media_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['art_vivantID']],
      foreignColumns: [art_vivant.id],
      name: 'payload_locked_documents_rels_art_vivant_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['cinemaID']],
      foreignColumns: [cinema.id],
      name: 'payload_locked_documents_rels_cinema_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['mediathequeID']],
      foreignColumns: [mediatheque.id],
      name: 'payload_locked_documents_rels_mediatheque_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['expositionID']],
      foreignColumns: [exposition.id],
      name: 'payload_locked_documents_rels_exposition_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['parc_nationalID']],
      foreignColumns: [parc_national.id],
      name: 'payload_locked_documents_rels_parc_national_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['autres_actualitesID']],
      foreignColumns: [autres_actualites.id],
      name: 'payload_locked_documents_rels_autres_actualites_fk',
    }).onDelete('cascade'),
  ],
)

export const payload_preferences = pgTable(
  'payload_preferences',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    key: varchar('key'),
    value: jsonb('value'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payload_preferences_key_idx').on(columns.key),
    index('payload_preferences_updated_at_idx').on(columns.updatedAt),
    index('payload_preferences_created_at_idx').on(columns.createdAt),
  ],
)

export const payload_preferences_rels = pgTable(
  'payload_preferences_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: uuid('parent_id').notNull(),
    path: varchar('path').notNull(),
    adminsID: uuid('mdv_admins_id'),
  },
  (columns) => [
    index('payload_preferences_rels_order_idx').on(columns.order),
    index('payload_preferences_rels_parent_idx').on(columns.parent),
    index('payload_preferences_rels_path_idx').on(columns.path),
    index('payload_preferences_rels_mdv_admins_id_idx').on(columns.adminsID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_preferences.id],
      name: 'payload_preferences_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['adminsID']],
      foreignColumns: [mdv_admins.id],
      name: 'payload_preferences_rels_admins_fk',
    }).onDelete('cascade'),
  ],
)

export const payload_migrations = pgTable(
  'payload_migrations',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    name: varchar('name'),
    batch: numeric('batch', { mode: 'number' }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payload_migrations_updated_at_idx').on(columns.updatedAt),
    index('payload_migrations_created_at_idx').on(columns.createdAt),
  ],
)

export const hours_closed_dates = pgTable(
  'hours_closed_dates',
  {
    _order: integer('_order').notNull(),
    _parentID: uuid('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    date: timestamp('date', { mode: 'string', withTimezone: true, precision: 3 }).notNull(),
  },
  (columns) => [
    index('hours_closed_dates_order_idx').on(columns._order),
    index('hours_closed_dates_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [hours.id],
      name: 'hours_closed_dates_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const hours = pgTable('hours', {
  id: uuid('id').defaultRandom().primaryKey(),
  horaires_base_base_start: timestamp('horaires_base_base_start', {
    mode: 'string',
    withTimezone: true,
    precision: 3,
  }).notNull(),
  horaires_base_base_end: timestamp('horaires_base_base_end', {
    mode: 'string',
    withTimezone: true,
    precision: 3,
  }).notNull(),
  horaires_base_dimanche_start: timestamp('horaires_base_dimanche_start', {
    mode: 'string',
    withTimezone: true,
    precision: 3,
  }).notNull(),
  horaires_base_dimanche_end: timestamp('horaires_base_dimanche_end', {
    mode: 'string',
    withTimezone: true,
    precision: 3,
  }).notNull(),
  horaires_ete_ete_date_from: timestamp('horaires_ete_ete_date_from', {
    mode: 'string',
    withTimezone: true,
    precision: 3,
  }).notNull(),
  horaires_ete_ete_date_to: timestamp('horaires_ete_ete_date_to', {
    mode: 'string',
    withTimezone: true,
    precision: 3,
  }).notNull(),
  horaires_ete_ete_start: timestamp('horaires_ete_ete_start', {
    mode: 'string',
    withTimezone: true,
    precision: 3,
  }).notNull(),
  horaires_ete_ete_end: timestamp('horaires_ete_ete_end', {
    mode: 'string',
    withTimezone: true,
    precision: 3,
  }).notNull(),
  horaires_hiver_noel_date_from: timestamp('horaires_hiver_noel_date_from', {
    mode: 'string',
    withTimezone: true,
    precision: 3,
  }).notNull(),
  horaires_hiver_noel_date_to: timestamp('horaires_hiver_noel_date_to', {
    mode: 'string',
    withTimezone: true,
    precision: 3,
  }).notNull(),
  horaires_hiver_fevrier_date_from: timestamp('horaires_hiver_fevrier_date_from', {
    mode: 'string',
    withTimezone: true,
    precision: 3,
  }).notNull(),
  horaires_hiver_fevrier_date_to: timestamp('horaires_hiver_fevrier_date_to', {
    mode: 'string',
    withTimezone: true,
    precision: 3,
  }).notNull(),
  horaires_hiver_hiver_start: timestamp('horaires_hiver_hiver_start', {
    mode: 'string',
    withTimezone: true,
    precision: 3,
  }).notNull(),
  horaires_hiver_hiver_end: timestamp('horaires_hiver_hiver_end', {
    mode: 'string',
    withTimezone: true,
    precision: 3,
  }).notNull(),
  updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 }),
  createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 }),
})

export const relations_mdv_admins_sessions = relations(mdv_admins_sessions, ({ one }) => ({
  _parentID: one(mdv_admins, {
    fields: [mdv_admins_sessions._parentID],
    references: [mdv_admins.id],
    relationName: 'sessions',
  }),
}))
export const relations_mdv_admins = relations(mdv_admins, ({ many }) => ({
  sessions: many(mdv_admins_sessions, {
    relationName: 'sessions',
  }),
}))
export const relations_mdv_media_locales = relations(mdv_media_locales, ({ one }) => ({
  _parentID: one(mdv_media, {
    fields: [mdv_media_locales._parentID],
    references: [mdv_media.id],
    relationName: '_locales',
  }),
}))
export const relations_mdv_media = relations(mdv_media, ({ many }) => ({
  _locales: many(mdv_media_locales, {
    relationName: '_locales',
  }),
}))
export const relations_art_vivant_other_images = relations(art_vivant_other_images, ({ one }) => ({
  _parentID: one(art_vivant, {
    fields: [art_vivant_other_images._parentID],
    references: [art_vivant.id],
    relationName: 'other_images',
  }),
  image: one(mdv_media, {
    fields: [art_vivant_other_images.image],
    references: [mdv_media.id],
    relationName: 'image',
  }),
}))
export const relations_art_vivant_locales = relations(art_vivant_locales, ({ one }) => ({
  _parentID: one(art_vivant, {
    fields: [art_vivant_locales._parentID],
    references: [art_vivant.id],
    relationName: '_locales',
  }),
}))
export const relations_art_vivant = relations(art_vivant, ({ one, many }) => ({
  thumbnail: one(mdv_media, {
    fields: [art_vivant.thumbnail],
    references: [mdv_media.id],
    relationName: 'thumbnail',
  }),
  other_images: many(art_vivant_other_images, {
    relationName: 'other_images',
  }),
  _locales: many(art_vivant_locales, {
    relationName: '_locales',
  }),
}))
export const relations_cinema_other_images = relations(cinema_other_images, ({ one }) => ({
  _parentID: one(cinema, {
    fields: [cinema_other_images._parentID],
    references: [cinema.id],
    relationName: 'other_images',
  }),
  image: one(mdv_media, {
    fields: [cinema_other_images.image],
    references: [mdv_media.id],
    relationName: 'image',
  }),
}))
export const relations_cinema_locales = relations(cinema_locales, ({ one }) => ({
  _parentID: one(cinema, {
    fields: [cinema_locales._parentID],
    references: [cinema.id],
    relationName: '_locales',
  }),
}))
export const relations_cinema = relations(cinema, ({ one, many }) => ({
  thumbnail: one(mdv_media, {
    fields: [cinema.thumbnail],
    references: [mdv_media.id],
    relationName: 'thumbnail',
  }),
  other_images: many(cinema_other_images, {
    relationName: 'other_images',
  }),
  _locales: many(cinema_locales, {
    relationName: '_locales',
  }),
}))
export const relations_mediatheque_other_images = relations(
  mediatheque_other_images,
  ({ one }) => ({
    _parentID: one(mediatheque, {
      fields: [mediatheque_other_images._parentID],
      references: [mediatheque.id],
      relationName: 'other_images',
    }),
    image: one(mdv_media, {
      fields: [mediatheque_other_images.image],
      references: [mdv_media.id],
      relationName: 'image',
    }),
  }),
)
export const relations_mediatheque_locales = relations(mediatheque_locales, ({ one }) => ({
  _parentID: one(mediatheque, {
    fields: [mediatheque_locales._parentID],
    references: [mediatheque.id],
    relationName: '_locales',
  }),
}))
export const relations_mediatheque = relations(mediatheque, ({ one, many }) => ({
  thumbnail: one(mdv_media, {
    fields: [mediatheque.thumbnail],
    references: [mdv_media.id],
    relationName: 'thumbnail',
  }),
  other_images: many(mediatheque_other_images, {
    relationName: 'other_images',
  }),
  _locales: many(mediatheque_locales, {
    relationName: '_locales',
  }),
}))
export const relations_exposition_images = relations(exposition_images, ({ one }) => ({
  _parentID: one(exposition, {
    fields: [exposition_images._parentID],
    references: [exposition.id],
    relationName: 'images',
  }),
  image: one(mdv_media, {
    fields: [exposition_images.image],
    references: [mdv_media.id],
    relationName: 'image',
  }),
}))
export const relations_exposition_other_images = relations(exposition_other_images, ({ one }) => ({
  _parentID: one(exposition, {
    fields: [exposition_other_images._parentID],
    references: [exposition.id],
    relationName: 'other_images',
  }),
  image: one(mdv_media, {
    fields: [exposition_other_images.image],
    references: [mdv_media.id],
    relationName: 'image',
  }),
}))
export const relations_exposition_locales = relations(exposition_locales, ({ one }) => ({
  _parentID: one(exposition, {
    fields: [exposition_locales._parentID],
    references: [exposition.id],
    relationName: '_locales',
  }),
}))
export const relations_exposition = relations(exposition, ({ one, many }) => ({
  images: many(exposition_images, {
    relationName: 'images',
  }),
  thumbnail: one(mdv_media, {
    fields: [exposition.thumbnail],
    references: [mdv_media.id],
    relationName: 'thumbnail',
  }),
  other_images: many(exposition_other_images, {
    relationName: 'other_images',
  }),
  _locales: many(exposition_locales, {
    relationName: '_locales',
  }),
}))
export const relations_parc_national_other_images = relations(
  parc_national_other_images,
  ({ one }) => ({
    _parentID: one(parc_national, {
      fields: [parc_national_other_images._parentID],
      references: [parc_national.id],
      relationName: 'other_images',
    }),
    image: one(mdv_media, {
      fields: [parc_national_other_images.image],
      references: [mdv_media.id],
      relationName: 'image',
    }),
  }),
)
export const relations_parc_national_locales = relations(parc_national_locales, ({ one }) => ({
  _parentID: one(parc_national, {
    fields: [parc_national_locales._parentID],
    references: [parc_national.id],
    relationName: '_locales',
  }),
}))
export const relations_parc_national = relations(parc_national, ({ one, many }) => ({
  thumbnail: one(mdv_media, {
    fields: [parc_national.thumbnail],
    references: [mdv_media.id],
    relationName: 'thumbnail',
  }),
  other_images: many(parc_national_other_images, {
    relationName: 'other_images',
  }),
  _locales: many(parc_national_locales, {
    relationName: '_locales',
  }),
}))
export const relations_autres_actualites_other_images = relations(
  autres_actualites_other_images,
  ({ one }) => ({
    _parentID: one(autres_actualites, {
      fields: [autres_actualites_other_images._parentID],
      references: [autres_actualites.id],
      relationName: 'other_images',
    }),
    image: one(mdv_media, {
      fields: [autres_actualites_other_images.image],
      references: [mdv_media.id],
      relationName: 'image',
    }),
  }),
)
export const relations_autres_actualites_locales = relations(
  autres_actualites_locales,
  ({ one }) => ({
    _parentID: one(autres_actualites, {
      fields: [autres_actualites_locales._parentID],
      references: [autres_actualites.id],
      relationName: '_locales',
    }),
  }),
)
export const relations_autres_actualites = relations(autres_actualites, ({ one, many }) => ({
  thumbnail: one(mdv_media, {
    fields: [autres_actualites.thumbnail],
    references: [mdv_media.id],
    relationName: 'thumbnail',
  }),
  other_images: many(autres_actualites_other_images, {
    relationName: 'other_images',
  }),
  _locales: many(autres_actualites_locales, {
    relationName: '_locales',
  }),
}))
export const relations_payload_kv = relations(payload_kv, () => ({}))
export const relations_payload_locked_documents_rels = relations(
  payload_locked_documents_rels,
  ({ one }) => ({
    parent: one(payload_locked_documents, {
      fields: [payload_locked_documents_rels.parent],
      references: [payload_locked_documents.id],
      relationName: '_rels',
    }),
    adminsID: one(mdv_admins, {
      fields: [payload_locked_documents_rels.adminsID],
      references: [mdv_admins.id],
      relationName: 'admins',
    }),
    mediaID: one(mdv_media, {
      fields: [payload_locked_documents_rels.mediaID],
      references: [mdv_media.id],
      relationName: 'media',
    }),
    art_vivantID: one(art_vivant, {
      fields: [payload_locked_documents_rels.art_vivantID],
      references: [art_vivant.id],
      relationName: 'art_vivant',
    }),
    cinemaID: one(cinema, {
      fields: [payload_locked_documents_rels.cinemaID],
      references: [cinema.id],
      relationName: 'cinema',
    }),
    mediathequeID: one(mediatheque, {
      fields: [payload_locked_documents_rels.mediathequeID],
      references: [mediatheque.id],
      relationName: 'mediatheque',
    }),
    expositionID: one(exposition, {
      fields: [payload_locked_documents_rels.expositionID],
      references: [exposition.id],
      relationName: 'exposition',
    }),
    parc_nationalID: one(parc_national, {
      fields: [payload_locked_documents_rels.parc_nationalID],
      references: [parc_national.id],
      relationName: 'parc_national',
    }),
    autres_actualitesID: one(autres_actualites, {
      fields: [payload_locked_documents_rels.autres_actualitesID],
      references: [autres_actualites.id],
      relationName: 'autres_actualites',
    }),
  }),
)
export const relations_payload_locked_documents = relations(
  payload_locked_documents,
  ({ many }) => ({
    _rels: many(payload_locked_documents_rels, {
      relationName: '_rels',
    }),
  }),
)
export const relations_payload_preferences_rels = relations(
  payload_preferences_rels,
  ({ one }) => ({
    parent: one(payload_preferences, {
      fields: [payload_preferences_rels.parent],
      references: [payload_preferences.id],
      relationName: '_rels',
    }),
    adminsID: one(mdv_admins, {
      fields: [payload_preferences_rels.adminsID],
      references: [mdv_admins.id],
      relationName: 'admins',
    }),
  }),
)
export const relations_payload_preferences = relations(payload_preferences, ({ many }) => ({
  _rels: many(payload_preferences_rels, {
    relationName: '_rels',
  }),
}))
export const relations_payload_migrations = relations(payload_migrations, () => ({}))
export const relations_hours_closed_dates = relations(hours_closed_dates, ({ one }) => ({
  _parentID: one(hours, {
    fields: [hours_closed_dates._parentID],
    references: [hours.id],
    relationName: 'closed_dates',
  }),
}))
export const relations_hours = relations(hours, ({ many }) => ({
  closed_dates: many(hours_closed_dates, {
    relationName: 'closed_dates',
  }),
}))

type DatabaseSchema = {
  enum__locales: typeof enum__locales
  enum_art_vivant_type: typeof enum_art_vivant_type
  enum_cinema_type: typeof enum_cinema_type
  enum_cinema_public: typeof enum_cinema_public
  enum_mediatheque_type: typeof enum_mediatheque_type
  enum_mediatheque_players: typeof enum_mediatheque_players
  enum_mediatheque_duration: typeof enum_mediatheque_duration
  enum_mediatheque_public: typeof enum_mediatheque_public
  enum_exposition_type: typeof enum_exposition_type
  enum_parc_national_type: typeof enum_parc_national_type
  enum_autres_actualites_type: typeof enum_autres_actualites_type
  mdv_admins_sessions: typeof mdv_admins_sessions
  mdv_admins: typeof mdv_admins
  mdv_media: typeof mdv_media
  mdv_media_locales: typeof mdv_media_locales
  art_vivant_other_images: typeof art_vivant_other_images
  art_vivant: typeof art_vivant
  art_vivant_locales: typeof art_vivant_locales
  cinema_other_images: typeof cinema_other_images
  cinema: typeof cinema
  cinema_locales: typeof cinema_locales
  mediatheque_other_images: typeof mediatheque_other_images
  mediatheque: typeof mediatheque
  mediatheque_locales: typeof mediatheque_locales
  exposition_images: typeof exposition_images
  exposition_other_images: typeof exposition_other_images
  exposition: typeof exposition
  exposition_locales: typeof exposition_locales
  parc_national_other_images: typeof parc_national_other_images
  parc_national: typeof parc_national
  parc_national_locales: typeof parc_national_locales
  autres_actualites_other_images: typeof autres_actualites_other_images
  autres_actualites: typeof autres_actualites
  autres_actualites_locales: typeof autres_actualites_locales
  payload_kv: typeof payload_kv
  payload_locked_documents: typeof payload_locked_documents
  payload_locked_documents_rels: typeof payload_locked_documents_rels
  payload_preferences: typeof payload_preferences
  payload_preferences_rels: typeof payload_preferences_rels
  payload_migrations: typeof payload_migrations
  hours_closed_dates: typeof hours_closed_dates
  hours: typeof hours
  relations_mdv_admins_sessions: typeof relations_mdv_admins_sessions
  relations_mdv_admins: typeof relations_mdv_admins
  relations_mdv_media_locales: typeof relations_mdv_media_locales
  relations_mdv_media: typeof relations_mdv_media
  relations_art_vivant_other_images: typeof relations_art_vivant_other_images
  relations_art_vivant_locales: typeof relations_art_vivant_locales
  relations_art_vivant: typeof relations_art_vivant
  relations_cinema_other_images: typeof relations_cinema_other_images
  relations_cinema_locales: typeof relations_cinema_locales
  relations_cinema: typeof relations_cinema
  relations_mediatheque_other_images: typeof relations_mediatheque_other_images
  relations_mediatheque_locales: typeof relations_mediatheque_locales
  relations_mediatheque: typeof relations_mediatheque
  relations_exposition_images: typeof relations_exposition_images
  relations_exposition_other_images: typeof relations_exposition_other_images
  relations_exposition_locales: typeof relations_exposition_locales
  relations_exposition: typeof relations_exposition
  relations_parc_national_other_images: typeof relations_parc_national_other_images
  relations_parc_national_locales: typeof relations_parc_national_locales
  relations_parc_national: typeof relations_parc_national
  relations_autres_actualites_other_images: typeof relations_autres_actualites_other_images
  relations_autres_actualites_locales: typeof relations_autres_actualites_locales
  relations_autres_actualites: typeof relations_autres_actualites
  relations_payload_kv: typeof relations_payload_kv
  relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels
  relations_payload_locked_documents: typeof relations_payload_locked_documents
  relations_payload_preferences_rels: typeof relations_payload_preferences_rels
  relations_payload_preferences: typeof relations_payload_preferences
  relations_payload_migrations: typeof relations_payload_migrations
  relations_hours_closed_dates: typeof relations_hours_closed_dates
  relations_hours: typeof relations_hours
}

declare module '@payloadcms/db-vercel-postgres' {
  export interface GeneratedDatabaseSchema {
    schema: DatabaseSchema
  }
}
